### ISSUE TITLE
changes I want you to approve

### ISSUE THREAD

**Issue by idokin** [idokin/KTech1#3]
@drorpc I moved the nav bar down a little and exposed a thin blue strip at the top. tell me what you think..if you dont like I can just move the text down and bring it back to normal

**Comment by idokin** [comment]
@drorpc made a bunch of more changes to same area of the site, take a look

**Comment by drorpc** [comment]
I want a darker background . couldn't see the data recovery website. @idokin

**Comment by idokin** [comment]
we agreed data recovery isn't our focus
